Bring back Schematron preprocessing.
For #26, pulling into master branch changes after a PR review was
complete clobbered these changes when my git client rebased. My
intermediary errors like this, while debugging further, made me take
notice that I had not stashed or properly saved these changes in my
branch.

using saxon version 10.2
SAXON_CP env variable used is /Users/astein/.m2/repository/net/sf/saxon/Saxon-HE/10.2/Saxon-HE-10.2.jar
Saxon JAR at classpath /Users/astein/.m2/repository/net/sf/saxon/Saxon-HE/10.2/Saxon-HE-10.2.jar is valid
Schema implementation error: This schema has abstract patterns, yet they are supposed to be preprocessed out already
Error: unrecognized element in ISO Schematron namespace: check spelling and capitalizationsch:param
Error: unrecognized element in ISO Schematron namespace: check spelling and capitalizationsch:param

These changes were tested on the tasks/issue-2-dynamic-requirement-counts branch.